"""
trainingSim.py
---------------
Main script to TRAIN the self driving car model.
Flow: Import CSV -> Balance data -> Load data -> Train/Val split
      -> Train NVIDIA CNN using batch generator -> Save model.h5

Folder structure expected:
    myData/
        IMG/                 <- all images from simulator go here
        driving_log.csv      <- log file generated by simulator
    utils.py
    model.py
    trainingSim.py
"""

print('Setting Up')
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'   # suppress TF info/warning logs

from utils import *
from model import createModel
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# -------------------------------------------------
# STEP 1: Import + inspect data
# -------------------------------------------------
path = 'myData'
data = importDataInfo(path)

# -------------------------------------------------
# STEP 2: Balance data (remove excess straight-driving samples)
# -------------------------------------------------
data = balanceData(data, display=True)

# -------------------------------------------------
# STEP 3: Load image paths + steering values as numpy arrays
# -------------------------------------------------
imagesPath, steerings = loadData(path, data)

# -------------------------------------------------
# STEP 4: Split into training (80%) and validation (20%)
# -------------------------------------------------
xTrain, xVal, yTrain, yVal = train_test_split(
    imagesPath, steerings, test_size=0.2, random_state=5
)
print('Total Training Images:', len(xTrain))
print('Total Validation Images:', len(xVal))

# -------------------------------------------------
# STEP 5: Create the NVIDIA model
# -------------------------------------------------
model = createModel()
model.summary()

# -------------------------------------------------
# STEP 6: Train using batch generator
#   - trainFlag=True  -> applies Pan/Zoom/Brightness/Flip augmentation
#   - trainFlag=False -> validation, NO augmentation (must test on real data)
# -------------------------------------------------
history = model.fit(
    batchGen(xTrain, yTrain, 100, True),
    steps_per_epoch=300,
    epochs=15,
    validation_data=batchGen(xVal, yVal, 100, False),
    validation_steps=200
)

# -------------------------------------------------
# STEP 7: Save the model
# -------------------------------------------------
model.save('model.h5')
print('Model Saved')

# -------------------------------------------------
# STEP 8: Plot training vs validation loss
# (accuracy dekhne ka best tareeka -> loss curve, kyunki yeh regression hai)
# -------------------------------------------------
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.legend(['Training', 'Validation'])
plt.title('Loss')
plt.xlabel('Epoch')
plt.show()